import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// custom logo font
const logoFont = localFont({
  src: "fonts/ElfEmmaAndTheTinySpider.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={logoFont.className}>
      <body>{children}</body>
    </html>
  );
}
